### ISSUE TITLE
Erro no npm install e npm start

### ISSUE THREAD

**Issue by jkleber** [pedroherpeto/zapdasgalaxias#10]
**Está aparecendo o seguinte erro após digitar npm install:**
...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'dialogflow-fulfillment@0.6.1',
npm WARN EBADENGINE   required: { node: '6' },
npm WARN EBADENGINE   current: { node: 'v20.12.0', npm: '10.5.0' }
npm WARN EBADENGINE }
...
npm WARN deprecated puppeteer@13.6.0: < 21.8.0 is no longer supported

added 517 packages, and audited 518 packages in 1m

59 packages are looking for funding
  run `npm fund` for details

33 vulnerabilities (3 low, 10 moderate, 16 high, 4 critical)

**->Quando digito npm start aparece esse erro**:
const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                             
TypeError: Cannot read properties of null (reading '1')

Alguém poderia ajudar?

**Comment by marcelolohamann** [comment]
Também estou com o mesmo problema rodando localmente e na vps. 
Pelo que sei esse é o criador do whatsapp-web.js https://github.com/pedroslopez/whatsapp-web.js/issues e lá também relataram o mesmo problema. Mas ela teve algumas atualizações a dois dias.

Será que a api comunidadezdg recebeu as atualizações, talvez seja esse o problema.

**Comment by marcelolohamann** [comment]
Api do pedroslopes mesmo erros

E:\xampp\htdocs\TVON-integrator\comunidadezdg\whatsapp-web.js\src\webCache\LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (E:\xampp\htdocs\TVON-integrator\comunidadezdg\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at E:\xampp\htdocs\TVON-integrator\comunidadezdg\whatsapp-web.js\src\Client.js:771:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1

**Comment by marcelolohamann** [comment]
SOLUÇÂO:
Olá a todos! Para instalar o patch, execute:

npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

A razão pela qual ainda não foi fundida é porque ainda estou trabalhando na estabilidade.

**Comment by marcelolohamann** [comment]
> SOLUÇÂO: Olá a todos! Para instalar o patch, execute:
> 
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> 
> A razão pela qual ainda não foi fundida é porque ainda estou trabalhando na estabilidade.

Funcionou localmente e na vps, agora só esperar a publicação da nova versão de correção.

**Comment by marcelolohamann** [comment]
Link da solução oficial https://github.com/pedroslopez/whatsapp-web.js/issues/2789
