### ISSUE TITLE
Não gera qrcode

### ISSUE THREAD

**Issue by andresouza1807** [pedroherpeto/zapdasgalaxias#7]
ReferenceError: socket is not defined
    at /www/wwwroot/comunidadezdg/botzdg.js:58:9
    at /www/wwwroot/comunidadezdg/node_modules/qrcode/lib/renderer/png.js:29:5
    at exports.PNG.<anonymous> (/www/wwwroot/comunidadezdg/node_modules/qrcode/lib/renderer/png.js:49:5)
    at exports.PNG.emit (events.js:400:28)
    at module.exports.emit (events.js:400:28)
    at module.exports.<anonymous> (/www/wwwroot/comunidadezdg/node_modules/pngjs/lib/packer-async.js:45:12)
    at Deflate.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

![qrcode error](https://github.com/pedroherpeto/comunidadezdg/assets/68432447/594f6f52-01ae-4ae8-9607-42e410d0187f)

Alguem pode me ajudar, nao consegui resolver.

**Comment by Isaider62** [comment]
Estou com o mesmo problema. Utilizei o painel da Hostinger
