### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by araujo-mateus** [pedroherpeto/zapdasgalaxias#8]
Galera, na hora de dar npm start, aparece esse erro:

[root@xxxxxxxx]# npm start

> bot-zdg@1.0.0 start
> node botzdg.js

Aplicação rodando na porta *: 8000 . Acesse no link: http://localhost:8000

/www/wwwroot/API/whatsjs/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[1120/144550.935190:ERROR:command_line_handler.cc(137)] Could not create directory /www/wwwroot/API/whatsjs/.wwebjs_auth/session: Permission denied (13)

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/www/wwwroot/API/whatsjs/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/www/wwwroot/API/whatsjs/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:526:35)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.17.1

**Comment by araujo-mateus** [comment]
Resolvido, bastou eu mudar o folder para home e atualizar permissões

**Comment by rafa82as** [comment]
> Resolvido, bastou eu mudar o folder para home e atualizar permissões

Pode me explicar melhor o que mudou? Sou um pouco leigo!
